# Generated by Django 3.1.7 on 2021-03-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sch', '0005_auto_20210321_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_at',
            field=models.DateField(verbose_name='Init Date'),
        ),
    ]
